#! /bin/bash

# Locations of stuff
python=/opt/64bit/bin/python
guppi_dir=/data1/demorest/guppi_daq
guppi_bin_dir=$guppi_dir/bin
guppi_python_dir=$guppi_dir/python

# Important vars
export PYTHONPATH=/opt/64bit/lib/python:/opt/64bit/lib/python/site-packages:/opt/64bit/presto/lib/python
export LD_LIBRARY_PATH=/opt/64bit/lib:/opt/64bit/pgplot:/opt/64bit/presto/lib

# Start monitor
$python $guppi_python_dir/guppi_simple_monitor.py $@
