#! /bin/bash

# Locations of stuff
python=/opt/64bit/bin/python
guppi_dir=/data1/demorest/guppi_daq
guppi_bin_dir=$guppi_dir/bin
guppi_python_dir=$guppi_dir/python

# Important vars
export PYTHONPATH=/opt/64bit/lib/python:/opt/64bit/lib/python/site-packages:/opt/64bit/presto/lib/python
export LD_LIBRARY_PATH=/opt/64bit/lib:/opt/64bit/pgplot:/opt/64bit/presto/lib

# Run to make sure status shmem exists
$guppi_bin_dir/check_guppi_status > /dev/null

# Run to make sure databuf exists
$guppi_bin_dir/check_guppi_databuf -c 2>/dev/null > /dev/null

# Fill params in
$python $guppi_python_dir/guppi_set_params_parspec.py

# Start data flow
$guppi_bin_dir/test_net_thread -p 4001 -s 2056 192.168.3.10 &

# Start monitor
$python $guppi_python_dir/guppi_simple_monitor.py

# When that exits, kill data flow
pkill -INT test_net_thread
