#ifndef __guppi_daq_cmd__
#define __guppi_daq_cmd__
/*****
  command line parser interface -- generated by clig 
  (http://wsd.iitb.fhg.de/~geg/clighome/)

  The command line parser `clig':
  (C) 1995-2004 Harald Kirsch (clig@geggus.net)
*****/

typedef struct s_Cmdline {
  /***** -outchan: Number of output frequency channels (combining if necessary) */
  char outchanP;
  int outchan;
  int outchanC;
  /***** -downsamp: Number of samples to average in time (defaults to none) */
  char downsampP;
  int downsamp;
  int downsampC;
  /***** -port: Port number for UDP packets */
  char portP;
  int port;
  int portC;
  /***** -size: UDP packet size (bytes) */
  char sizeP;
  int size;
  int sizeC;
  /***** -host: Hostname of the data taking instrument */
  char hostnameP;
  char* hostname;
  int hostnameC;
  /***** uninterpreted command line parameters */
  int argc;
  /*@null*/char **argv;
  /***** the whole command line concatenated */
  char *full_cmd_line;
} Cmdline;


extern char *Program;
extern void usage(void);
extern /*@shared*/Cmdline *parseCmdline(int argc, char **argv);

extern void showOptionValues(void);

#endif

