#ifndef __guppi_daq_cmd__
#define __guppi_daq_cmd__
/*****
  command line parser interface -- generated by clig 
  (http://wsd.iitb.fhg.de/~geg/clighome/)

  The command line parser `clig':
  (C) 1995-2004 Harald Kirsch (clig@geggus.net)
*****/

typedef struct s_Cmdline {
  /***** -outchan: Number of output frequency channels (combining if necessary) */
  char outchanP;
  int outchan;
  int outchanC;
  /***** -downsamp: Number of samples to average in time (defaults to none) */
  char downsampP;
  int downsamp;
  int downsampC;
  /***** uninterpreted command line parameters */
  int argc;
  /*@null*/char **argv;
  /***** the whole command line concatenated */
  char *full_cmd_line;
} Cmdline;


extern char *Program;
extern void usage(void);
extern /*@shared*/Cmdline *parseCmdline(int argc, char **argv);

#endif

